package main

import (
	"bytes"
	"crypto"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/binary"
	"encoding/pem"
	"fmt"
	"log"
	"os"
)

// MCUboot Header & Configuration Constants
const (
	ImageMagic       uint32 = 0x96f3b83d
	TlvInfoMagic     uint16 = 0x6907
	TlvSha256        uint8  = 0x10
	TlvRsa2048       uint8  = 0x20
	HeaderSize       uint16 = 0x400
	SlotSize         int    = 1540096 // From your --slot-size flag
)

// ImageVersion matches your --version 1.0.1+0 flag
type ImageVersion struct {
	Major    uint8
	Minor    uint8
	Revision uint16
	BuildNum uint32
}

// ImageHeader represents the 32-byte MCUboot header
type ImageHeader struct {
	Magic     uint32
	LoadAddr  uint32
	HdrSize   uint16
	PTLVSize  uint16 // Protected TLV size (0 if unused)
	ImageSize uint32 // Size of the actual application payload
	Flags     uint32 // Flags (0x0 is fine; --overwrite-only is handled by omitting swap trailers)
	Version   ImageVersion
	Pad1      uint32
}

func main() {
	// 1. Read the pre-padded binary from Zephyr
	fileData, err := os.ReadFile("zephyr.bin")
	if err != nil {
		log.Fatalf("Failed to read input binary: %v", err)
	}

	if len(fileData) < int(HeaderSize) {
		log.Fatalf("Input file is too small to contain the 0x400 header space")
	}

	// 2. Load and parse the RSA Private Key
	keyFile, err := os.ReadFile("root-rsa-2048.pem")
	if err != nil {
		log.Fatalf("Failed to read key: %v", err)
	}

	block, _ := pem.Decode(keyFile)
	if block == nil {
		log.Fatalf("Failed to parse PEM block")
	}
	
	privKey, err := x509.ParsePKCS1PrivateKey(block.Bytes)
	if err != nil {
		log.Fatalf("Failed to parse RSA key: %v", err)
	}

	// 3. Slice off the empty header space generated by the Zephyr linker
	actualPayload := fileData[HeaderSize:]

	// 4. Construct the MCUboot Header
	header := ImageHeader{
		Magic:     ImageMagic,
		LoadAddr:  0x0,
		HdrSize:   HeaderSize,
		PTLVSize:  0,
		ImageSize: uint32(len(actualPayload)), // Now correctly evaluates to 0x68364
		Flags:     0x0, 
		Version: ImageVersion{
			Major:    1,
			Minor:    0,
			Revision: 1,
			BuildNum: 0,
		},
	}

	// 5. Buffer to construct the final signed image
	var img bytes.Buffer

	// Write the header struct in Little Endian
	err = binary.Write(&img, binary.LittleEndian, header)
	if err != nil {
		log.Fatalf("Failed to write header: %v", err)
	}

	// Pad the rest of the 0x400 header area with 0xFF
	padding := make([]byte, HeaderSize-uint16(img.Len()))
	for i := range padding {
		padding[i] = 0x00
	}
	img.Write(padding)

	// Write the actual application payload
	img.Write(actualPayload)

	// 6. Calculate SHA-256 Hash of Header + Padding + Payload
	hash := sha256.Sum256(img.Bytes())

	// 7. Generate RSA-PSS Signature
	signature, err := rsa.SignPSS(rand.Reader, privKey, crypto.SHA256, hash[:], &rsa.PSSOptions{
		SaltLength: rsa.PSSSaltLengthEqualsHash,
	})
	if err != nil {
		log.Fatalf("Failed to sign payload: %v", err)
	}

	// 8. Append TLV Trailer
	appendTLVs(&img, hash[:], signature)

	// 9. Size Validation (Replicating Zephyr's safety check)
	totalImageSize := img.Len()
	if totalImageSize > SlotSize {
		log.Fatalf("Error: Final image size (%d) exceeds the defined slot size (%d)!", totalImageSize, SlotSize)
	}

	// 10. Save the final signed binary
	err = os.WriteFile("zephyr.signed.bin", img.Bytes(), 0644)
	if err != nil {
		log.Fatalf("Failed to write output: %v", err)
	}
	
	fmt.Println("Image successfully signed!")
	fmt.Printf("Payload size: %d bytes (0x%X)\n", len(actualPayload), len(actualPayload))
	fmt.Printf("Total size:   %d bytes\n", totalImageSize)
}

// appendTLVs handles the trailer struct packing (Little Endian)
func appendTLVs(img *bytes.Buffer, hash []byte, sig []byte) {
	// Calculate total TLV size: InfoHeader(4) + SHA256(4 + 32) + RSA(4 + 256) = 300 bytes
	binary.Write(img, binary.LittleEndian, TlvInfoMagic)
	binary.Write(img, binary.LittleEndian, uint16(300))

	// Write SHA256 TLV (Type, Reserved padding, Length, Value)
	binary.Write(img, binary.LittleEndian, TlvSha256)
	binary.Write(img, binary.LittleEndian, uint8(0)) 
	binary.Write(img, binary.LittleEndian, uint16(len(hash)))
	img.Write(hash)

	// Write RSA Signature TLV (Type, Reserved padding, Length, Value)
	binary.Write(img, binary.LittleEndian, TlvRsa2048)
	binary.Write(img, binary.LittleEndian, uint8(0)) 
	binary.Write(img, binary.LittleEndian, uint16(len(sig)))
	img.Write(sig)
}
